model:
  latent_dim: 128  # Default latent dimension
  input_channels: 3  # RGB images

data:
  root_dir: "data/celeba/img_align_celeba"
  attr_path: "data/celeba/list_attr_celeba.txt"
  image_size: 128  # Keep this for good face detail

training:
  # Basic training parameters
  num_epochs: 5
  batch_size: 128
  learning_rate: 0.001
  weight_decay: 0  # L2 regularization
  kl_weight: 0.00025  # KL divergence weight
  
  # Cross-validation parameters
  cross_validation:
    enabled: true
    sample_size: 20000  # Number of samples to use for CV
    n_folds: 5  # Number of folds for k-fold CV
    dimensions: [64, 128, 256]  # Dimensions to test
  
  # Resource utilization
  num_workers: 8
  prefetch_factor: 2
  
  # Checkpointing and logging
  save_interval: 10
  checkpoint_dir: "checkpoints"
  log_dir: "logs"
  log_interval: 100
  save_best_only: true
  early_stopping_patience: 25
  
  # Learning rate scheduler
  scheduler:
    name: "plateau"
    params:
      mode: "min"
      factor: 0.3
      patience: 2
      threshold: 0.00001
      threshold_mode: "rel"
      cooldown: 1
      min_lr: 0.000001
  
  # GPU optimization
  mixed_precision: true
  cudnn_benchmark: true
  multi_gpu: true
  pin_memory: true
  gradient_accumulation_steps: 1
  max_grad_norm: 0.5

evaluation:
  metrics:
    - "psnr"
    - "ssim"
    - "mse"
  validation_interval: 1
  validation_split: 0.1 